title: EARSHOT

email: info@earhost.xyz

description: > # this means to ignore newlines until "baseurl:"
  the range or distance over which one can hear or be heard

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: earshot-xyz

github_username:  earshot-xyz

google_analytics: UA-59367601-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

info:
  name: "Earshot srls"
  address: "largo delle acque 2x"
  cap: 00018
  city: "Palombara Sabina"
  country: Roma
  state: IT
  piva: 13046121003
