# general configuration
url: http://earshot.xyz
baseurl: ''

# earshot configuration
earshot:
  # an avatar or logo (optional)
  logo: "/images/ear.png"
  touch: "/images/ear_bg_I.png"
  # author will appear under the avatar (optional)
  author: "earshot"
  # titlepage (optional)
  titlepage: "hearing distance"
  # tagline will appear under the title (optional)
  tagline: "the range or distance over which one can hear or be heard"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Google Analytics
analytics:
  # Add tracking code in _includes/_google-analytics.html
  google: false
